type: ppocr_table_v4
name: ch_PP-OCRv4_TableRec (PaddleOCR + Table Recognition)

use_gpu: False

# params for prediction engine
ppocr_models:
    use_onnx: True
    use_openvino: False
    use_tensorrt: False
    min_subgraph_size: 15
    precision: fp32

    det_model:
        det_algorithm: DB
        det_model_path: models/ch_ppocr_table_rec/ch_PP-OCRv4_det_infer.onnx
        det_db_thresh: 0.3
        det_db_box_thresh: 0.6
        det_db_unclip_ratio: 1.5
        max_batch_size: 10
        use_dilation: False
        det_db_score_mode: fast
        det_limit_side_len: 960
        det_limit_type: max
        det_box_type: quad

    rec_model:
        rec_algorithm: SVTR_LCNet
        rec_model_path: models/ch_ppocr_table_rec/ch_PP-OCRv4_rec_infer.onnx
        rec_batch_num: 6 
        rec_image_inverse: True
        rec_image_shape: "3, 48, 320"
        max_text_length: 25
        rec_char_dict_path: pipelines/configs/ppocr_keys_v1.txt
        use_space_char: True
        drop_score: 0.5

table_model:
    table_max_len: 488
    table_algorithm: TableAttn
    table_model_path: models/ch_ppocr_table_rec/ch_ppstructure_mobile_v2.0_SLANet_infer.onnx
    preprocess_params:
        - ResizeTableImage:
            max_len: 488
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: hwc
        - PaddingTableImage:
            size: [488, 488]
        - ToCHWImage: 
            img: None
        - KeepKeys:
            keep_keys: [image, shape]
    postprocess_params:
        character_dict_path: pipelines/configs/table_structure_dict_ch.txt
        merge_no_span_structure: true